# Étape de construction
FROM node:16-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

# Transpile TypeScript en JavaScript
RUN npm run build

# Étape de production
FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist ./dist

CMD ["node", "dist/src/app.js"]
